name: "ga-example"

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Hello world
        run: echo "Hello world! - $NAME"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Second hellow world
        run: echo "Second Hellow world! - ${{ github.ref }}"

  third-job:
    runs-on: ubuntu-latest

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        run: ls -al

  fourth-job:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub output
        run: echo $GITHUB_OUTPUT
