name: "ga-example"

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito

    steps:
      - name: Hello world
        run: echo "Hello world! - $NAME"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Second hellow world
        run: echo "Second Hellow world! - ${{ github.ref }}"
