name: "ga-example"

on:
  push:
    branches: ["main"]

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello world!"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Second hellow world
        run: echo "Second Hellow world!"
